05_Django/Django_Git_Project/03_model/ws_c/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login')
]

05_Django/Django_Git_Project/03_model/ws_c/todo_list_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls')),
    path('accounts/', include('accounts.urls')),
]

05_Django/Django_Git_Project/03_model/ws_c/todos/urls.py
from django.urls import path
from . import views


app_name = 'todos'

urlpatterns = [
    path('', views.index, name='index'),
    path('create_todo/', views.create_todo, name='create_todo'),
    path('<work>/', views.detail, name='detail'),
]

05_Django/Django_Git_Project/03_model/ws_c/todos/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    work = models.CharField(max_length=100)
    content = models.TextField()
    is_completed = models.BooleanField()

05_Django/Django_Git_Project/03_model/ws_c/accounts/views.py
from django.shortcuts import render

# Create your views here.
def login(request):
    return render(request, 'accounts/login.html')

05_Django/Django_Git_Project/03_model/ws_c/todos/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    work = request.GET.get('work')
    context = {
        'work': work
    }
    return render(request, 'todos/index.html', context)

def create_todo(request):
    return render(request, 'todos/create_todo.html')

def detail(request, work):
    context = {
        'work': work
    }
    return render(request, 'todos/detail.html', context)

05_Django/Django_Git_Project/03_model/ws_c/todos/templates/todos/create_todo.html
{% extends "base.html" %}

{% block content %}
  <h1>이 곳에서 할 일을 생성합니다.</h1>
  <p>추후 기능 추가 예정</p>

  <form action="{% url "todos:index" %}">
    <input type="text" name="work">
    <input type="submit" value="제출">
  </form>
{% endblock content %}

05_Django/Django_Git_Project/03_model/ws_c/todos/templates/todos/detail.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ work }} 상세 페이지</h1>
{% endblock content %}

05_Django/Django_Git_Project/03_model/ws_c/todos/templates/todos/index.html
{% extends "base.html" %}

{% block content %}
  <h1>할 일 목록 관리 프로젝트 메인 페이지</h1>
  <p>이 곳에서 할 일 목록을 관리합니다.</p>
  <ul>
    {% if work %}
      <li><a href="{% url "todos:detail" work %}">{{ work }}</a></li>
    {% else %}
      <li>아직 할 일이 없습니다.</li>
    {% endif %}
  </ul>
{% endblock content %}