05_Django/Django_Git_Project/05_ORM_with_view/ws_04/garages/urls.py
from django.urls import path
from . import views


app_name = 'garages'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    # create에 요청이 들어왔을때, create view 함수가 실행
    path('create/', views.create, name='create'),
    path('<int:garage_pk>/', views.detail, name='detail'),
    # path('create/', views.create, name='create'),
    # path('create/', views.create, name='create'),
    # path('create/', views.create, name='create'),
]

05_Django/Django_Git_Project/05_ORM_with_view/ws_04/parking_management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('garages/', include('garages.urls')),
]

05_Django/Django_Git_Project/05_ORM_with_view/ws_04/garages/models.py
from django.db import models

# Create your models here.
class Garage(models.Model):
    location = models.CharField(max_length=200)
    capacity = models.IntegerField()
    is_parking_avaliable = models.BooleanField()
    opening_time = models.TimeField()
    closing_time = models.TimeField()

05_Django/Django_Git_Project/05_ORM_with_view/ws_04/garages/views.py
from django.shortcuts import render, redirect
from .models import Garage

# Create your views here.
def index(request):
    # 전체 차고지 정보
    # Model.manager.querySet API()
    # all 메서드 호출 결과를 garages 변수에 할당하고,
    garages = Garage.objects.all()
    context = {
        'garages': garages
    }
    return render(request, 'garages/index.html', context)

def new(request):
    return render(request, 'garages/new.html')

def create(request):
    # 사용자의 요청 정보를 모두 담고 있는 request를 사용해서
    # 사용자가 POST 방식으로 보내온 데이터들
    '''
        request.POST => {
            'location' : value
            'capacity' : value
            'is_parking_avaliable' : value
            'opening_time' : value
            'closing_time': value
            } 
    '''
    location = request.POST.get('location')
    capacity = request.POST.get('capacity')
    is_parking_avaliable = request.POST.get('is_parking_avaliable')
    opening_time = request.POST.get('opening_time')
    closing_time = request.POST.get('closing_time')

    garage = Garage(location=location, capacity=capacity,is_parking_avaliable=is_parking_avaliable,opening_time=opening_time,closing_time=closing_time)
    garage.save()
    return redirect('garages:index')

def detail(request, garage_pk):
    # pk 값이 사용자가 요청보내욘 pk 값을 가지고 있는 데이터 하나
    garage = Garage.objects.get(pk=garage_pk)
    context = {
        'garage': garage
    }
    return render(request, 'garages/detail.html', context)

05_Django/Django_Git_Project/05_ORM_with_view/ws_04/garages/templates/garages/detail.html
{% extends "base.html" %}

{% block content %}
  <h1>상세 페이지</h1>
  <p>{{ garage.pk }}</p>
  <p>{{ garage.location }}</p>
  <p>{{ garage.capacity }}</p>
  <p>{{ garage.is_parking_avaliable }}</p>
  <p>{{ garage.opening_time }}</p>
  <p>{{ garage.closing_time }}</p>
{% endblock content %}  

05_Django/Django_Git_Project/05_ORM_with_view/ws_04/garages/templates/garages/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>주차 정보 관리 시스템</h1>
  <!-- app_name:url_name -->
  <a href="{% url "garages:new" %}"> [NEW] </a>
  <p>모든 차고지 정보</p>
  <ul>
  {% for garage in garages %}
    <li>위치 : {{ garage.location }}</li>
    <li>주차 가능 대 수 : {{ garage.capacity }}</li>
    <li>현재 주차 가능 여부 : {{ garage.is_parking_avaliable }}</li>
    <hr>
  {% endfor %}
  </ul>
{% endblock content %}

05_Django/Django_Git_Project/05_ORM_with_view/ws_04/garages/templates/garages/new.html
{% extends 'base.html' %}

{% block content %}
  <h1>신규 차고 등록</h1>
  <form action="{% url 'garages:create' %}" method="POST">
  {% comment %} <form method="POST"> {% endcomment %}
    {% csrf_token %}
    <label for="location">위치 : </label>
    <input type="text" id="location" name="location"><br>

    <label for="capacity">주차 가능 차량 수 : </label>
    <input type="number" id="capacity" name="capacity"><br>

    <p for="is_parking_avaliable">주차 가능 여부</p>
    <label for="is_parking_avaliable_true">가능</label>
    <input type="radio" id="is_parking_avaliable_true" name="is_parking_avaliable" value="True">

    <label for="is_parking_avaliable_false">불가능</label>
    <input type="radio" id="is_parking_avaliable_false" name="is_parking_avaliable" value="False"><br>

    <label for="opening_time">여는 시간 : </label>
    <input type="time" id="opening_time" name="opening_time"><br>

    <label for="closing_time">닫는 시간 : </label>
    <input type="time" id="closing_time" name="closing_time"><br>

    <input type="submit" value='제출'>
  </form>
{% endblock content %}